### ISSUE TITLE
Make sure minutes conform to SE.QA.03

### ISSUE THREAD

**Issue by dkmonaghan** [aber-cs22120-group-15/docs#1]
Section 2 in SE.QA.03 outlines how minutes need to be formatted. The minutes for previous meetings need to be edited to make sure they conform to these standards.

**Comment by dkmonaghan** [comment]
@chriswloftus Does this need to be done on a week by week basis or can all minutes be edited at the end to conform to the standard?

**Comment by chriswloftus** [comment]
Every week. It ensures that the minutes are accurate and easy to read
Chris
